'use client';

import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  English: {
    dashboard: 'Overview Dashboard',
    assistant: 'Voter Assistant',
    candidates: 'Candidate Profiler',
    pulse: 'Election Pulse',
    map: 'Civic Map',
    mapDesc: 'Find your nearest polling station and view local representatives.',
    manifesto: 'Manifesto Analyzer',
    civicScore: 'Civic Score',
    topVoters: 'Top 5% of Voters',
    timelineDesc: 'Projected Statutory Timeline: Delimitation 2026 & General Elections 2029',
    analyzeManifesto: 'Analyze Manifesto',
    eduSimulation: '⚠️ Educational Simulation: This dashboard projects timelines for the upcoming 2026 Delimitation process and the subsequent General Elections. Data reflects statutory processes, not live real-time metrics.',
    daysToElection: 'Days to Election',
    phase1: 'Phase 1 Begins Soon',
    registeredVoters: 'Registered Voters',
    from2024: '+1.5% from 2024',
    pollingStations: 'Polling Stations',
    allLocationsVerified: 'All locations verified',
    officialSchedule: 'Official Election Schedule',
    t1: 'Delimitation Commission Formed',
    t2: 'Constituency Boundaries Published',
    t3: 'Special Summary Revision of Electoral Rolls',
    t4: 'Final Publication of Voter List',
    t5: 'Announcement of Polling Dates',
    pulseDesc: 'Real-time news and AI-driven sentiment analysis.',
    aiSentiment: 'AI SENTIMENT ANALYSIS',
    latestNews: 'Latest Breaking News',
    candidatesDesc: 'Verified financial and criminal records from official affidavits.',
    complianceNotice: 'Compliance Notice: This data is sourced from self-sworn affidavits filed by candidates with the Election Commission of India (ECI). Information regarding criminal cases refers to pending cases and does not imply conviction. This platform is for educational purposes only.',
    financialDec: 'Financial Declaration',
    assets: 'Assets',
    liabilities: 'Liabilities',
    education: 'Education',
    criminalRecord: 'Criminal Record',
    pendingCases: 'Pending Cases',
    cleanRecord: 'Clean Record',
    legisPerf: 'Legislative Performance',
    attendance: 'Attendance',
    debates: 'Debates',
    voterAI: 'Voter Education AI',
    askQuestion: 'Ask a question about voting...',
    searching: 'Searching knowledge base...',
    eduDisclaimer: 'Educational tool only. Not affiliated with the Election Commission of India. Always verify official dates and facts at ',
    clearChat: 'Clear Chat'
  },
  Hindi: {
    dashboard: 'सिंहावलोकन डैशबोर्ड',
    assistant: 'मतदाता सहायक',
    candidates: 'उम्मीदवार प्रोफाइलर',
    pulse: 'चुनाव पल्स',
    map: 'नागरिक मानचित्र',
    mapDesc: 'अपना निकटतम मतदान केंद्र खोजें और स्थानीय प्रतिनिधियों को देखें।',
    manifesto: 'घोषणापत्र विश्लेषक',
    civicScore: 'नागरिक स्कोर',
    topVoters: 'शीर्ष 5% मतदाता',
    timelineDesc: 'अनुमानित वैधानिक समयरेखा: परिसीमन 2026 और आम चुनाव 2029',
    analyzeManifesto: 'घोषणापत्र का विश्लेषण करें',
    eduSimulation: '⚠️ शैक्षिक सिमुलेशन: यह डैशबोर्ड आगामी 2026 परिसीमन प्रक्रिया और उसके बाद के आम चुनावों के लिए समयसीमा का अनुमान लगाता है। डेटा वैधानिक प्रक्रियाओं को दर्शाता है, लाइव रीयल-टाइम मेट्रिक्स को नहीं।',
    daysToElection: 'चुनाव में दिन',
    phase1: 'चरण 1 जल्द शुरू होगा',
    registeredVoters: 'पंजीकृत मतदाता',
    from2024: '2024 से +1.5%',
    pollingStations: 'मतदान केंद्र',
    allLocationsVerified: 'सभी स्थानों का सत्यापन',
    officialSchedule: 'आधिकारिक चुनाव कार्यक्रम',
    t1: 'परिसीमन आयोग का गठन',
    t2: 'निर्वाचन क्षेत्र की सीमाएं प्रकाशित',
    t3: 'मतदाता सूचियों का विशेष संक्षिप्त पुनरीक्षण',
    t4: 'मतदाता सूची का अंतिम प्रकाशन',
    t5: 'मतदान की तारीखों की घोषणा',
    pulseDesc: 'वास्तविक समय की खबरें और एआई-संचालित भावना विश्लेषण।',
    aiSentiment: 'एआई भावना विश्लेषण',
    latestNews: 'ताज़ा ब्रेकिंग न्यूज़',
    candidatesDesc: 'आधिकारिक हलफनामों से सत्यापित वित्तीय और आपराधिक रिकॉर्ड।',
    complianceNotice: 'अनुपालन सूचना: यह डेटा उम्मीदवारों द्वारा भारत के चुनाव आयोग (ECI) में दायर किए गए स्व-शपथ हलफनामों से प्राप्त किया गया है। आपराधिक मामलों के संबंध में जानकारी का अर्थ लंबित मामले हैं और इसका अर्थ दोषसिद्धि नहीं है। यह मंच केवल शैक्षिक उद्देश्यों के लिए है।',
    financialDec: 'वित्तीय घोषणा',
    assets: 'संपत्ति',
    liabilities: 'देनदारियां',
    education: 'शिक्षा',
    criminalRecord: 'आपराधिक रिकॉर्ड',
    pendingCases: 'लंबित मामले',
    cleanRecord: 'स्वच्छ रिकॉर्ड',
    legisPerf: 'विधायी प्रदर्शन',
    attendance: 'उपस्थिति',
    debates: 'बहस',
    voterAI: 'मतदाता शिक्षा एआई',
    askQuestion: 'मतदान के बारे में प्रश्न पूछें...',
    searching: 'ज्ञानकोष खोजा जा रहा है...',
    eduDisclaimer: 'केवल शैक्षिक उपकरण। भारत के चुनाव आयोग से संबद्ध नहीं। आधिकारिक तिथियों और तथ्यों को हमेशा सत्यापित करें ',
    clearChat: 'चैट साफ़ करें'
  },
  Gujarati: {
    dashboard: 'વિહંગાવલોકન ડેશબોર્ડ',
    assistant: 'મતદાતા સહાયક',
    candidates: 'ઉમેદવાર પ્રોફાઇલર',
    pulse: 'ચૂંટણી પલ્સ',
    map: 'નાગરિક નકશો',
    mapDesc: 'તમારું નજીકનું મતદાન મથક શોધો અને સ્થાનિક પ્રતિનિધિઓ જુઓ.',
    manifesto: 'મેનિફેસ્ટો વિશ્લેષક',
    civicScore: 'નાગરિક સ્કોર',
    topVoters: 'ટોચના 5% મતદારો',
    timelineDesc: 'અંદાજિત વૈધાનિક સમયરેખા: સીમાંકન 2026 અને સામાન્ય ચૂંટણી 2029',
    analyzeManifesto: 'મેનિફેસ્ટોનું વિશ્લેષણ કરો',
    eduSimulation: '⚠️ શૈક્ષણિક સિમ્યુલેશન: આ ડેશબોર્ડ આગામી 2026 સીમાંકન પ્રક્રિયા અને ત્યારબાદની સામાન્ય ચૂંટણીઓ માટે સમયરેખા રજૂ કરે છે. ડેટા વૈધાનિક પ્રક્રિયાઓ દર્શાવે છે, લાઇવ રીઅલ-ટાઇમ મેટ્રિક્સ નહીં.',
    daysToElection: 'ચૂંટણીના દિવસો',
    phase1: 'તબક્કો 1 ટૂંક સમયમાં શરૂ થશે',
    registeredVoters: 'નોંધાયેલા મતદારો',
    from2024: '2024 થી +1.5%',
    pollingStations: 'મતદાન મથકો',
    allLocationsVerified: 'બધા સ્થાનો ચકાસાયેલ છે',
    officialSchedule: 'સત્તાવાર ચૂંટણી કાર્યક્રમ',
    t1: 'સીમાંકન પંચની રચના',
    t2: 'મતવિસ્તારની સીમાઓ પ્રકાશિત',
    t3: 'મતદાર યાદીઓની ખાસ સંક્ષિપ્ત સુધારણા',
    t4: 'મતદાર યાદીનું અંતિમ પ્રકાશન',
    t5: 'મતદાનની તારીખોની જાહેરાત',
    pulseDesc: 'રીઅલ-ટાઇમ સમાચાર અને AI-આધારિત સેન્ટિમેન્ટ વિશ્લેષણ.',
    aiSentiment: 'AI સેન્ટિમેન્ટ વિશ્લેષણ',
    latestNews: 'તાજા બ્રેકિંગ ન્યૂઝ',
    candidatesDesc: 'સત્તાવાર એફિડેવિટમાંથી ચકાસાયેલ નાણાકીય અને ફોજદારી રેકોર્ડ્સ.',
    complianceNotice: 'પાલન સૂચના: આ ડેટા ભારતના ચૂંટણી પંચ (ECI) પાસે ઉમેદવારો દ્વારા દાખલ કરાયેલ સ્વ-સોગંદનામામાંથી લેવામાં આવ્યો છે. ફોજદારી કેસો અંગેની માહિતી પેન્ડિંગ કેસોનો સંદર્ભ આપે છે અને તે દોષિત ઠરાવતો નથી. આ પ્લેટફોર્મ માત્ર શૈક્ષણિક હેતુઓ માટે છે.',
    financialDec: 'નાણાકીય ઘોષણા',
    assets: 'સંપત્તિ',
    liabilities: 'જવાબદારીઓ',
    education: 'શિક્ષણ',
    criminalRecord: 'ફોજદારી રેકોર્ડ',
    pendingCases: 'પેન્ડિંગ કેસ',
    cleanRecord: 'ક્લીન રેકોર્ડ',
    legisPerf: 'કાયદાકીય કામગીરી',
    attendance: 'હાજરી',
    debates: 'ચર્ચાઓ',
    voterAI: 'મતદાતા શિક્ષણ AI',
    askQuestion: 'મતદાન વિશે પ્રશ્ન પૂછો...',
    searching: 'નોલેજ બેઝ શોધી રહ્યું છે...',
    eduDisclaimer: 'ફક્ત શૈક્ષણિક સાધન. ભારતના ચૂંટણી પંચ સાથે જોડાયેલ નથી. હંમેશા સત્તાવાર તારીખો અને તથ્યો ચકાસો ',
    clearChat: 'ચેટ સાફ કરો'
  },
  Marathi: {
    dashboard: 'आढावा डॅशबोर्ड',
    assistant: 'मतदार सहाय्यक',
    candidates: 'उमेदवार प्रोफाइलर',
    pulse: 'निवडणूक पल्स',
    map: 'नागरी नकाशा',
    mapDesc: 'तुमचे जवळचे मतदान केंद्र शोधा आणि स्थानिक प्रतिनिधी पहा.',
    manifesto: 'जाहीरनामा विश्लेषक',
    civicScore: 'नागरी स्कोअर',
    topVoters: 'शीर्ष 5% मतदार',
    timelineDesc: 'अंदाजित वैधानिक टाइमलाइन: परिसीमन 2026 आणि सार्वत्रिक निवडणुका 2029',
    analyzeManifesto: 'जाहीरनाम्याचे विश्लेषण करा',
    eduSimulation: '⚠️ शैक्षणिक सिम्युलेशन: हे डॅशबोर्ड आगामी 2026 परिसीमन प्रक्रिया आणि त्यानंतरच्या सार्वत्रिक निवडणुकांसाठी वेळेचा अंदाज लावते. डेटा वैधानिक प्रक्रिया दर्शवतो, थेट रिअल-टाइम मेट्रिक्स नाही.',
    daysToElection: 'निवडणुकीचे दिवस',
    phase1: 'टप्पा 1 लवकरच सुरू होईल',
    registeredVoters: 'नोंदणीकृत मतदार',
    from2024: '2024 पासून +1.5%',
    pollingStations: 'मतदान केंद्रे',
    allLocationsVerified: 'सर्व स्थाने सत्यापित',
    officialSchedule: 'अधिकृत निवडणूक वेळापत्रक',
    t1: 'परिसीमन आयोगाची स्थापना',
    t2: 'मतदारसंघाच्या सीमा प्रकाशित',
    t3: 'मतदार याद्यांची विशेष संक्षिप्त उजळणी',
    t4: 'मतदार यादीचे अंतिम प्रकाशन',
    t5: 'मतदानाच्या तारखांची घोषणा',
    pulseDesc: 'रिअल-टाइम बातम्या आणि एआय-चालित भावना विश्लेषण.',
    aiSentiment: 'एआय भावना विश्लेषण',
    latestNews: 'ताज्या ब्रेकिंग न्यूज',
    candidatesDesc: 'अधिकृत प्रतिज्ञापत्रांमधून सत्यापित आर्थिक आणि गुन्हेगारी नोंदी.',
    complianceNotice: 'अनुपालन सूचना: हा डेटा उमेदवारांनी भारतीय निवडणूक आयोगाकडे (ECI) दाखल केलेल्या स्वयं-शपथ प्रतिज्ञापत्रांमधून मिळवला आहे. गुन्हेगारी प्रकरणांसंबंधी माहिती प्रलंबित प्रकरणांचा संदर्भ देते आणि याचा अर्थ दोषसिद्धी होत नाही. हे व्यासपीठ केवळ शैक्षणिक हेतूंसाठी आहे.',
    financialDec: 'आर्थिक घोषणा',
    assets: 'मालमत्ता',
    liabilities: 'दायित्वे',
    education: 'शिक्षण',
    criminalRecord: 'गुन्हेगारी रेकॉर्ड',
    pendingCases: 'प्रलंबित प्रकरणे',
    cleanRecord: 'स्वच्छ रेकॉर्ड',
    legisPerf: 'विधानसभेतील कामगिरी',
    attendance: 'उपस्थिती',
    debates: 'वादविवाद',
    voterAI: 'मतदार शिक्षण एआय',
    askQuestion: 'मतदानाबद्दल प्रश्न विचारा...',
    searching: 'नॉलेज बेस शोधत आहे...',
    eduDisclaimer: 'केवळ शैक्षणिक साधन. भारताच्या निवडणूक आयोगाशी संलग्न नाही. अधिकृत तारखा आणि तथ्ये नेहमी सत्यापित करा ',
    clearChat: 'चॅट साफ करा'
  },
  Tamil: {
    dashboard: 'கண்ணோட்டம் டாஷ்போர்டு',
    assistant: 'வாக்காளர் உதவியாளர்',
    candidates: 'வேட்பாளர் புரொஃபைலர்',
    pulse: 'தேர்தல் பல்ஸ்',
    map: 'குடிமக்கள் வரைபடம்',
    mapDesc: 'உங்கள் அருகிலுள்ள வாக்குச் சாவடியைக் கண்டறிந்து உள்ளூர் பிரதிநிதிகளைப் பார்க்கவும்.',
    manifesto: 'தேர்தல் அறிக்கை பகுப்பாய்வி',
    civicScore: 'குடிமக்கள் மதிப்பெண்',
    topVoters: 'முதல் 5% வாக்காளர்கள்',
    timelineDesc: 'மதிப்பிடப்பட்ட சட்டப்பூர்வ காலக்கெடு: தொகுதி மறுசீரமைப்பு 2026 & பொதுத் தேர்தல்கள் 2029',
    analyzeManifesto: 'தேர்தல் அறிக்கையை பகுப்பாய்வு செய்',
    eduSimulation: '⚠️ கல்வி உருவகப்படுத்துதல்: இந்த டாஷ்போர்டு வரவிருக்கும் 2026 மறுசீரமைப்பு செயல்முறை மற்றும் பொதுத் தேர்தல்களுக்கான காலக்கெடுவை திட்டமிடுகிறது. தரவு சட்டப்பூர்வ செயல்முறைகளை பிரதிபலிக்கிறது, நேரடி நிகழ்நேர அளவீடுகளை அல்ல.',
    daysToElection: 'தேர்தலுக்கு உள்ள நாட்கள்',
    phase1: 'கட்டம் 1 விரைவில் தொடங்கும்',
    registeredVoters: 'பதிவு செய்யப்பட்ட வாக்காளர்கள்',
    from2024: '2024 இலிருந்து +1.5%',
    pollingStations: 'வாக்குச் சாவடிகள்',
    allLocationsVerified: 'அனைத்து இடங்களும் சரிபார்க்கப்பட்டன',
    officialSchedule: 'அதிகாரப்பூர்வ தேர்தல் அட்டவணை',
    t1: 'தொகுதி மறுசீரமைப்பு ஆணையம் அமைக்கப்பட்டது',
    t2: 'தொகுதி எல்லைகள் வெளியிடப்பட்டன',
    t3: 'வாக்காளர் பட்டியல்களின் சிறப்பு சுருக்கத் திருத்தம்',
    t4: 'வாக்காளர் பட்டியலின் இறுதி வெளியீடு',
    t5: 'வாக்குப்பதிவு தேதிகள் அறிவிப்பு',
    pulseDesc: 'நிகழ்நேர செய்திகள் மற்றும் AI-உந்துதல் உணர்வு பகுப்பாய்வு.',
    aiSentiment: 'AI உணர்வு பகுப்பாய்வு',
    latestNews: 'சமீபத்திய முக்கிய செய்திகள்',
    candidatesDesc: 'அதிகாரப்பூர்வ பிரமாணப் பத்திரங்களில் இருந்து சரிபார்க்கப்பட்ட நிதி மற்றும் குற்றவியல் பதிவுகள்.',
    complianceNotice: 'இணக்க அறிவிப்பு: இந்தத் தரவு இந்தியத் தேர்தல் ஆணையத்தில் (ECI) வேட்பாளர்கள் தாக்கல் செய்த சுய-பிரமாணப் பத்திரங்களிலிருந்து பெறப்பட்டது. கிரிமினல் வழக்குகளைப் பற்றிய தகவல்கள் நிலுவையில் உள்ள வழக்குகளைக் குறிக்கின்றன, மேலும் அவை குற்றவாளி என்று நிரூபிக்கப்பட்டதைக் குறிக்கவில்லை. இந்த தளம் கல்வி நோக்கங்களுக்காக மட்டுமே.',
    financialDec: 'நிதி அறிவிப்பு',
    assets: 'சொத்துக்கள்',
    liabilities: 'பொறுப்புகள்',
    education: 'கல்வி',
    criminalRecord: 'குற்றப் பதிவு',
    pendingCases: 'நிலுவையில் உள்ள வழக்குகள்',
    cleanRecord: 'சுத்தமான பதிவு',
    legisPerf: 'சட்டமன்ற செயல்பாடுகள்',
    attendance: 'வருகை',
    debates: 'விவாதங்கள்',
    voterAI: 'வாக்காளர் கல்வி AI',
    askQuestion: 'வாக்களிப்பது பற்றி ஒரு கேள்வி கேட்கவும்...',
    searching: 'அறிவுத் தளத்தைத் தேடுகிறது...',
    eduDisclaimer: 'கல்வி கருவி மட்டுமே. இந்திய தேர்தல் ஆணையத்துடன் இணைக்கப்படவில்லை. அதிகாரப்பூர்வ தேதிகள் மற்றும் உண்மைகளை எப்போதும் சரிபார்க்கவும் ',
    clearChat: 'அரட்டையை அழி'
  },
  Telugu: {
    dashboard: 'అవలోకనం డాష్‌బోర్డ్',
    assistant: 'ఓటరు అసిస్టెంట్',
    candidates: 'అభ్యర్థి ప్రొఫైలర్',
    pulse: 'ఎన్నికల పల్స్',
    map: 'సివిక్ మ్యాప్',
    mapDesc: 'మీ సమీప పోలింగ్ కేంద్రాన్ని కనుగొనండి మరియు స్థానిక ప్రతినిధులను వీక్షించండి.',
    manifesto: 'మేనిఫెస్టో ఎనలైజర్',
    civicScore: 'సివిక్ స్కోర్',
    topVoters: 'టాప్ 5% ఓటర్లు',
    timelineDesc: 'అంచనా వేయబడిన చట్టబద్ధమైన కాలక్రమం: డీలిమిటేషన్ 2026 & సాధారణ ఎన్నికలు 2029',
    analyzeManifesto: 'మేనిఫెస్టోను విశ్లేషించండి',
    eduSimulation: '⚠️ విద్యా అనుకరణ: ఈ డాష్‌బోర్డ్ రాబోయే 2026 డీలిమిటేషన్ ప్రక్రియ మరియు సాధారణ ఎన్నికల కోసం సమయపాలనలను అంచనా వేస్తుంది. డేటా చట్టబద్ధమైన ప్రక్రియలను ప్రతిబింబిస్తుంది, ప్రత్యక్ష నిజ-సమయ కొలమానాలను కాదు.',
    daysToElection: 'ఎన్నికలకు రోజులు',
    phase1: 'దశ 1 త్వరలో ప్రారంభమవుతుంది',
    registeredVoters: 'నమోదిత ఓటర్లు',
    from2024: '2024 నుండి +1.5%',
    pollingStations: 'పోలింగ్ కేంద్రాలు',
    allLocationsVerified: 'అన్ని స్థానాలు ధృవీకరించబడ్డాయి',
    officialSchedule: 'అధికారిక ఎన్నికల షెడ్యూల్',
    t1: 'డీలిమిటేషన్ కమిషన్ ఏర్పాటు',
    t2: 'నియోజకవర్గ సరిహద్దులు ప్రచురించబడ్డాయి',
    t3: 'ఓటరు జాబితాల ప్రత్యేక సారాంశ సవరణ',
    t4: 'ఓటరు జాబితా తుది ప్రచురణ',
    t5: 'పోలింగ్ తేదీల ప్రకటన',
    pulseDesc: 'నిజ-సమయ వార్తలు మరియు AI-ఆధారిత సెంటిమెంట్ విశ్లేషణ.',
    aiSentiment: 'AI సెంటిమెంట్ విశ్లేషణ',
    latestNews: 'తాజా బ్రేకింగ్ న్యూస్',
    candidatesDesc: 'అధికారిక అఫిడవిట్‌ల నుండి ధృవీకరించబడిన ఆర్థిక మరియు క్రిమినల్ రికార్డులు.',
    complianceNotice: 'సమ్మతి నోటీసు: ఈ డేటా అభ్యర్థులు భారత ఎన్నికల సంఘం (ECI)కి దాఖలు చేసిన స్వీయ-ప్రమాణ అఫిడవిట్‌ల నుండి సేకరించబడింది. క్రిమినల్ కేసులకు సంబంధించిన సమాచారం పెండింగ్‌లో ఉన్న కేసులను సూచిస్తుంది మరియు శిక్షను సూచించదు. ఈ ప్లాట్‌ఫారమ్ విద్యా ప్రయోజనాల కోసం మాత్రమే.',
    financialDec: 'ఆర్థిక ప్రకటన',
    assets: 'ఆస్తులు',
    liabilities: 'అప్పులు',
    education: 'విద్య',
    criminalRecord: 'క్రిమినల్ రికార్డ్',
    pendingCases: 'పెండింగ్ కేసులు',
    cleanRecord: 'క్లీన్ రికార్డ్',
    legisPerf: 'శాసనసభ పనితీరు',
    attendance: 'హాజరు',
    debates: 'చర్చలు',
    voterAI: 'ఓటరు విద్య AI',
    askQuestion: 'ఓటింగ్ గురించి ఒక ప్రశ్న అడగండి...',
    searching: 'నాలెడ్జ్ బేస్ వెతుకుతోంది...',
    eduDisclaimer: 'విద్యా సాధనం మాత్రమే. భారత ఎన్నికల సంఘంతో అనుబంధించబడలేదు. ఎల్లప్పుడూ అధికారిక తేదీలు మరియు వాస్తవాలను ధృవీకరించండి ',
    clearChat: 'చాట్ క్లియర్ చేయండి'
  },
  Bengali: {
    dashboard: 'ওভারভিউ ড্যাশবোর্ড',
    assistant: 'ভোটার সহকারী',
    candidates: 'প্রার্থী প্রোফাইলার',
    pulse: 'নির্বাচনী পালস',
    map: 'নাগরিক মানচিত্র',
    mapDesc: 'আপনার নিকটতম ভোটকেন্দ্র খুঁজুন এবং স্থানীয় প্রতিনিধিদের দেখুন।',
    manifesto: 'ইশতেহার বিশ্লেষক',
    civicScore: 'নাগরিক স্কোর',
    topVoters: 'শীর্ষ 5% ভোটার',
    timelineDesc: 'আনুমানিক সংবিধিবদ্ধ সময়সীমা: সীমানা নির্ধারণ 2026 এবং সাধারণ নির্বাচন 2029',
    analyzeManifesto: 'ইশতেহার বিশ্লেষণ করুন',
    eduSimulation: '⚠️ শিক্ষামূলক সিমুলেশন: এই ড্যাশবোর্ডটি আসন্ন 2026 সীমানা নির্ধারণ প্রক্রিয়া এবং পরবর্তী সাধারণ নির্বাচনের জন্য সময়সীমার প্রক্ষেপণ করে। ডেটা সংবিধিবদ্ধ প্রক্রিয়াগুলিকে প্রতিফলিত করে, লাইভ রিয়েল-টাইম মেট্রিক্স নয়।',
    daysToElection: 'নির্বাচনের দিন',
    phase1: 'ধাপ 1 শীঘ্রই শুরু হবে',
    registeredVoters: 'নিবন্ধিত ভোটার',
    from2024: '2024 থেকে +1.5%',
    pollingStations: 'ভোট কেন্দ্র',
    allLocationsVerified: 'সমস্ত অবস্থান যাচাই করা হয়েছে',
    officialSchedule: 'অফিসিয়াল নির্বাচনের সময়সূচী',
    t1: 'সীমানা নির্ধারণ কমিশন গঠিত',
    t2: 'নির্বাচনী এলাকার সীমানা প্রকাশিত',
    t3: 'ভোটার তালিকার বিশেষ সংক্ষিপ্ত সংশোধন',
    t4: 'ভোটার তালিকার চূড়ান্ত প্রকাশ',
    t5: 'ভোটের তারিখ ঘোষণা',
    pulseDesc: 'রিয়েল-টাইম খবর এবং এআই-চালিত আবেগ বিশ্লেষণ।',
    aiSentiment: 'এআই আবেগ বিশ্লেষণ',
    latestNews: 'সর্বশেষ ব্রেকিং নিউজ',
    candidatesDesc: 'অফিসিয়াল হলফনামা থেকে যাচাইকৃত আর্থিক এবং অপরাধমূলক রেকর্ড।',
    complianceNotice: 'সম্মতি বিজ্ঞপ্তি: এই ডেটা ভারতের নির্বাচন কমিশনে (ECI) প্রার্থীদের দ্বারা দায়ের করা স্ব-শপথ হলফনামা থেকে নেওয়া হয়েছে। ফৌজদারি মামলা সংক্রান্ত তথ্য বিচারাধীন মামলার উল্লেখ করে এবং দোষী সাব্যস্ত করা বোঝায় না। এই প্ল্যাটফর্মটি শুধুমাত্র শিক্ষামূলক উদ্দেশ্যে।',
    financialDec: 'আর্থিক ঘোষণা',
    assets: 'সম্পদ',
    liabilities: 'দায়',
    education: 'শিক্ষা',
    criminalRecord: 'অপরাধমূলক রেকর্ড',
    pendingCases: 'বিচারাধীন মামলা',
    cleanRecord: 'পরিষ্কার রেকর্ড',
    legisPerf: 'আইন প্রণয়নের পারফরম্যান্স',
    attendance: 'উপস্থিতি',
    debates: 'বিতর্ক',
    voterAI: 'ভোটার শিক্ষা এআই',
    askQuestion: 'ভোট সম্পর্কে একটি প্রশ্ন জিজ্ঞাসা করুন...',
    searching: 'নলেজ বেস অনুসন্ধান করা হচ্ছে...',
    eduDisclaimer: 'শুধুমাত্র শিক্ষামূলক টুল। ভারতের নির্বাচন কমিশনের সাথে যুক্ত নয়। সর্বদা অফিসিয়াল তারিখ এবং তথ্য যাচাই করুন ',
    clearChat: 'চ্যাট পরিষ্কার করুন'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('English');
  
  const t = (key) => {
    return translations[language]?.[key] || translations['English'][key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
